const express=require('express');const cors=require('cors');const path=require('path');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');
const app=express();const PORT=process.env.PORT||3000;const SECRET=process.env.JWT_SECRET||'change-this-secret-before-production';
const db=new Database(process.env.DB_PATH||path.join(__dirname,'handover.db'));
db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,name TEXT NOT NULL,title TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',dept TEXT NOT NULL);CREATE TABLE IF NOT EXISTS handovers(id INTEGER PRIMARY KEY AUTOINCREMENT,dept TEXT NOT NULL,shift TEXT NOT NULL,author_id INTEGER NOT NULL,recipient_id INTEGER NOT NULL,summary TEXT NOT NULL,todo TEXT NOT NULL,issue TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(author_id) REFERENCES users(id),FOREIGN KEY(recipient_id) REFERENCES users(id));CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,handover_id INTEGER NOT NULL,message TEXT NOT NULL,read_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(handover_id) REFERENCES handovers(id));`);
const departments=['倉庫部','拍賣部','物流部','資訊部'];const seed=[['warehouse_mgr','王志明','經理','倉庫部'],['warehouse_1','陳建宏','職員','倉庫部'],['warehouse_2','林冠廷','職員','倉庫部'],['auction_mgr','李明哲','經理','拍賣部'],['auction_1','張育誠','職員','拍賣部'],['auction_2','黃俊豪','職員','拍賣部'],['logistics_mgr','林志宏','經理','物流部'],['logistics_1','吳承翰','職員','物流部'],['logistics_2','許家豪','職員','物流部'],['it_mgr','周文傑','經理','資訊部'],['it_1','鄭宇翔','職員','資訊部'],['it_2','郭冠廷','職員','資訊部']];
const count=db.prepare('SELECT COUNT(*) n FROM users').get().n;if(!count){const ins=db.prepare('INSERT INTO users(username,password_hash,name,title,role,dept) VALUES(?,?,?,?,?,?)');const tx=db.transaction(()=>{ins.run('admin',bcrypt.hashSync('admin123',10),'系統管理者','系統管理者','admin','全部部門');for(const [u,n,t,d] of seed)ins.run(u,bcrypt.hashSync('1234',10),n,t,'user',d)});tx()}
app.use(cors());app.use(express.json({limit:'1mb'}));app.use(express.static(__dirname));
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:'未登入或登入已過期'})}}
function publicUser(u){return {id:u.id,username:u.username,name:u.name,title:u.title,role:u.role,dept:u.dept}}
app.post('/api/login',(req,res)=>{const {username,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE username=?').get(username);if(!u||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'帳號或密碼錯誤'});const token=jwt.sign({id:u.id,username:u.username,name:u.name,title:u.title,role:u.role,dept:u.dept},SECRET,{expiresIn:'12h'});res.json({token,user:publicUser(u)})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/users',auth,(req,res)=>{const rows=req.user.role==='admin'?db.prepare('SELECT * FROM users ORDER BY dept,title,name').all():db.prepare('SELECT * FROM users WHERE dept=? ORDER BY title DESC,name').all(req.user.dept);res.json(rows.map(publicUser))});
app.get('/api/handovers',auth,(req,res)=>{const rows=req.user.role==='admin'?db.prepare(`SELECT h.*,a.name author_name,a.title author_title,r.name recipient_name,r.title recipient_title FROM handovers h JOIN users a ON a.id=h.author_id JOIN users r ON r.id=h.recipient_id ORDER BY h.id DESC`).all():db.prepare(`SELECT h.*,a.name author_name,a.title author_title,r.name recipient_name,r.title recipient_title FROM handovers h JOIN users a ON a.id=h.author_id JOIN users r ON r.id=h.recipient_id WHERE h.dept=? ORDER BY h.id DESC`).all(req.user.dept);res.json(rows)});
app.post('/api/handovers',auth,(req,res)=>{const {shift,recipient_id,summary,todo='',issue=''}=req.body||{};if(!['早班','午班','夜班'].includes(shift)||!summary||!recipient_id)return res.status(400).json({error:'班別、交接對象與交接事項為必填'});const recipient=db.prepare('SELECT * FROM users WHERE id=?').get(recipient_id);if(!recipient)return res.status(400).json({error:'交接對象不存在'});if(req.user.role!=='admin'&&recipient.dept!==req.user.dept)return res.status(403).json({error:'只能交接給同部門人員'});const dept=req.user.role==='admin'?(req.body.dept||recipient.dept):req.user.dept;const now=new Date().toISOString();const result=db.prepare('INSERT INTO handovers(dept,shift,author_id,recipient_id,summary,todo,issue,created_at) VALUES(?,?,?,?,?,?,?,?)').run(dept,shift,req.user.id,recipient.id,String(summary).trim(),String(todo).trim()||'無',String(issue).trim()||'無',now);const msg=`${req.user.name}（${req.user.title}）將 ${dept} ${shift} 交接給您`;db.prepare('INSERT INTO notifications(user_id,handover_id,message,created_at) VALUES(?,?,?,?)').run(recipient.id,result.lastInsertRowid,msg,now);res.status(201).json({id:result.lastInsertRowid,message:'交接已儲存並通知交接對象'})});
app.get('/api/notifications',auth,(req,res)=>res.json(db.prepare(`SELECT n.*,h.dept,h.shift,h.summary,h.todo,h.issue,a.name author_name,a.title author_title FROM notifications n JOIN handovers h ON h.id=n.handover_id JOIN users a ON a.id=h.author_id WHERE n.user_id=? ORDER BY n.id DESC LIMIT 50`).all(req.user.id)));
app.post('/api/notifications/:id/read',auth,(req,res)=>{db.prepare('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?').run(new Date().toISOString(),req.params.id,req.user.id);res.json({ok:true})});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'handover-system',database:'sqlite'}));
app.listen(PORT,()=>console.log(`Handover System API running on http://localhost:${PORT}`));