const express=require('express');const cors=require('cors');const path=require('path');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');const multer=require('multer');const XLSX=require('xlsx');
const app=express();const PORT=process.env.PORT||3000;const SECRET=process.env.JWT_SECRET||'change-this-secret-before-production';
const db=new Database(process.env.DB_PATH||path.join(__dirname,'handover.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,name TEXT NOT NULL,title TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',dept TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS handovers(id INTEGER PRIMARY KEY AUTOINCREMENT,dept TEXT NOT NULL,shift TEXT NOT NULL,author_id INTEGER NOT NULL,recipient_id INTEGER NOT NULL,summary TEXT NOT NULL,todo TEXT NOT NULL,issue TEXT NOT NULL,today_price TEXT NOT NULL DEFAULT '',contribution TEXT NOT NULL DEFAULT '',market_data TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,FOREIGN KEY(author_id) REFERENCES users(id),FOREIGN KEY(recipient_id) REFERENCES users(id));CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,handover_id INTEGER NOT NULL,message TEXT NOT NULL,read_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(handover_id) REFERENCES handovers(id));`);
try{db.prepare("ALTER TABLE users ADD COLUMN active INTEGER NOT NULL DEFAULT 1").run()}catch(e){if(!String(e.message).includes('duplicate column'))throw e}
for(const sql of [`ALTER TABLE handovers ADD COLUMN today_price TEXT NOT NULL DEFAULT ''`,`ALTER TABLE handovers ADD COLUMN contribution TEXT NOT NULL DEFAULT ''`,`ALTER TABLE handovers ADD COLUMN market_data TEXT NOT NULL DEFAULT '{}'`]){try{db.prepare(sql).run()}catch(e){if(!String(e.message).includes('duplicate column'))throw e}}
try{db.prepare("UPDATE handovers SET contribution=today_price WHERE contribution='' AND today_price<>''").run()}catch(e){}
const seed=[['warehouse_mgr','王志明','經理','倉庫部'],['warehouse_1','陳建宏','職員','倉庫部'],['warehouse_2','林冠廷','職員','倉庫部'],['auction_mgr','李明哲','經理','拍賣部'],['auction_1','張育誠','職員','拍賣部'],['auction_2','黃俊豪','職員','拍賣部'],['logistics_mgr','林志宏','經理','物流部'],['logistics_1','吳承翰','職員','物流部'],['logistics_2','許家豪','職員','物流部'],['it_mgr','周文傑','經理','資訊部'],['it_1','鄭宇翔','職員','資訊部'],['it_2','郭冠廷','職員','資訊部'],['fruit_mgr','陳志偉','經理','水果組'],['fruit_1','林怡君','職員','水果組'],['fruit_2','黃柏勳','職員','水果組'],['vegetable_mgr','許文雄','經理','蔬菜組'],['vegetable_1','張雅雯','職員','蔬菜組'],['vegetable_2','吳俊逸','職員','蔬菜組']];
if(!db.prepare("SELECT 1 FROM users WHERE username='admin'").get())db.prepare('INSERT INTO users(username,password_hash,name,title,role,dept,active) VALUES(?,?,?,?,?,?,1)').run('admin',bcrypt.hashSync('admin123',10),'系統管理者','系統管理者','admin','全部部門');
const insSeed=db.prepare('INSERT INTO users(username,password_hash,name,title,role,dept,active) VALUES(?,?,?,?,?,?,1)');for(const [u,n,t,d] of seed){if(!db.prepare('SELECT 1 FROM users WHERE username=?').get(u))insSeed.run(u,bcrypt.hashSync('1234',10),n,t,'user',d)}
app.use(cors());app.use(express.json({limit:'1mb'}));app.use(express.static(__dirname));
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:'未登入或登入已過期'})}}
function adminOnly(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'只有系統管理者可以執行此操作'});next()}
function publicUser(u){return{id:u.id,username:u.username,name:u.name,title:u.title,role:u.role,dept:u.dept,active:!!u.active}}
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
const IMPORT_HEADERS=['部門名稱','員工工號(帳號)','中文姓名','職務名稱'];
function clean(v){return String(v??'').replace(/\uFEFF/g,'').trim()}
function normalizeHeader(h){return clean(h).replace(/[\s\u3000]/g,'').replace(/[（]/g,'(').replace(/[）]/g,')')}
function getImportRows(buffer){const wb=XLSX.read(buffer,{type:'buffer',cellDates:false});if(!wb.SheetNames.length)throw new Error('Excel 沒有工作表');const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});if(!rows.length)return{rows:[],sheet:wb.SheetNames[0]};const keys=Object.keys(rows[0]);const map={};for(const k of keys)map[normalizeHeader(k)]=k;for(const h of IMPORT_HEADERS){if(!map[normalizeHeader(h)])throw new Error(`缺少欄位：${h}`)}return{rows:rows.map(r=>({dept:clean(r[map[IMPORT_HEADERS[0]]]),username:clean(r[map[IMPORT_HEADERS[1]]]),name:clean(r[map[IMPORT_HEADERS[2]]]),title:clean(r[map[IMPORT_HEADERS[3]]])})),sheet:wb.SheetNames[0]}}
app.post('/api/login',(req,res)=>{const{username,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE username=?').get(clean(username));if(!u||!u.active||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'帳號或密碼錯誤，或帳號已停用'});const token=jwt.sign(publicUser(u),SECRET,{expiresIn:'12h'});res.json({token,user:publicUser(u)})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.post('/api/me/password',auth,(req,res)=>{const{currentPassword,newPassword}=req.body||{};if(!currentPassword||!newPassword)return res.status(400).json({error:'請填寫目前密碼與新密碼'});if(String(newPassword).length<4)return res.status(400).json({error:'新密碼至少 4 個字元'});const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);if(!u||!bcrypt.compareSync(currentPassword,u.password_hash))return res.status(400).json({error:'目前密碼錯誤'});db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(bcrypt.hashSync(String(newPassword),10),u.id);res.json({message:'密碼已修改，請重新登入'})});
app.get('/api/users',auth,(req,res)=>{const rows=req.user.role==='admin'?db.prepare('SELECT * FROM users WHERE active=1 ORDER BY dept,title,name').all():db.prepare('SELECT * FROM users WHERE dept=? AND active=1 ORDER BY title DESC,name').all(req.user.dept);res.json(rows.map(publicUser))});
app.get('/api/admin/users',auth,adminOnly,(req,res)=>res.json(db.prepare('SELECT id,username,name,title,role,dept,active FROM users ORDER BY dept,title,name').all().map(publicUser)));
app.post('/api/admin/users',auth,adminOnly,(req,res)=>{const{username,password,name,title,dept,role='user',active=1}=req.body||{};const u=clean(username),n=clean(name),t=clean(title),d=clean(dept);if(!u||!password||!n||!t||!d)return res.status(400).json({error:'帳號、密碼、姓名、職稱與部門為必填'});if(!['user','admin'].includes(role))return res.status(400).json({error:'權限設定錯誤'});if(db.prepare('SELECT 1 FROM users WHERE username=?').get(u))return res.status(409).json({error:'帳號已存在'});const r=db.prepare('INSERT INTO users(username,password_hash,name,title,role,dept,active) VALUES(?,?,?,?,?,?,?)').run(u,bcrypt.hashSync(String(password),10),n,t,role,d,active?1:0);res.status(201).json({id:r.lastInsertRowid,message:'使用者已建立'})});
app.put('/api/admin/users/:id',auth,adminOnly,(req,res)=>{const id=Number(req.params.id);const u=db.prepare('SELECT * FROM users WHERE id=?').get(id);if(!u)return res.status(404).json({error:'使用者不存在'});const{name,title,dept,role,active,password}=req.body||{};const n=clean(name),t=clean(title),d=clean(dept);if(!n||!t||!d||!['user','admin'].includes(role))return res.status(400).json({error:'姓名、職稱、部門與權限為必填'});if(id===req.user.id&&Number(active)===0)return res.status(400).json({error:'不能停用目前登入的管理者帳號'});if(id===req.user.id&&role!=='admin')return res.status(400).json({error:'不能移除目前登入帳號的管理者權限'});if(password&&String(password).trim())db.prepare('UPDATE users SET name=?,title=?,dept=?,role=?,active=?,password_hash=? WHERE id=?').run(n,t,d,role,active?1:0,bcrypt.hashSync(String(password),10),id);else db.prepare('UPDATE users SET name=?,title=?,dept=?,role=?,active=? WHERE id=?').run(n,t,d,role,active?1:0,id);res.json({message:'使用者資料已更新'})});
app.post('/api/admin/users/import',auth,adminOnly,upload.single('file'),(req,res)=>{try{if(!req.file)return res.status(400).json({error:'請選擇 Excel 檔案'});const{rows,sheet}=getImportRows(req.file.buffer);if(rows.length>500)return res.status(400).json({error:'單次最多匯入 500 筆'});const result={sheet,total:rows.length,created:0,skipped:0,errors:[],duplicates:[]};const existing=new Set(db.prepare('SELECT username FROM users').all().map(x=>x.username));const seen=new Set();const insert=db.prepare('INSERT INTO users(username,password_hash,name,title,role,dept,active) VALUES(?,?,?,?,?,?,1)');const tx=db.transaction(items=>{for(const [i,row] of items.entries()){const line=i+2;if(!row.dept||!row.username||!row.name||!row.title){result.errors.push(`第 ${line} 列：四個欄位皆必填`);continue}if(seen.has(row.username)){result.duplicates.push(`第 ${line} 列：工號 ${row.username} 在 Excel 內重複`);result.skipped++;continue}seen.add(row.username);if(existing.has(row.username)){result.duplicates.push(`第 ${line} 列：工號 ${row.username} 已存在，略過`);result.skipped++;continue}insert.run(row.username,bcrypt.hashSync('1234',10),row.name,row.title,'user',row.dept);existing.add(row.username);result.created++}});tx(rows);res.json({message:`Excel 匯入完成：新增 ${result.created} 人，略過 ${result.skipped} 人`,...result,passwordDefault:'1234'})}catch(e){res.status(400).json({error:e.message||'Excel 匯入失敗'})}});
app.get('/api/admin/users/template.csv',auth,adminOnly,(req,res)=>{res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="user-import-template.csv"');res.send('\uFEFF部門名稱,員工工號(帳號),中文姓名,職務名稱\r\n水果組,F001,王小明,水果組職員\r\n蔬菜組,V001,陳小華,蔬菜組職員\r\n')});
app.get('/api/handovers',auth,(req,res)=>{const sql=`SELECT h.*,a.name author_name,a.title author_title,r.name recipient_name,r.title recipient_title FROM handovers h JOIN users a ON a.id=h.author_id JOIN users r ON r.id=h.recipient_id`;const rows=req.user.role==='admin'?db.prepare(sql+' ORDER BY h.id DESC').all():db.prepare(sql+' WHERE h.dept=? ORDER BY h.id DESC').all(req.user.dept);res.json(rows)});
app.post('/api/handovers',auth,(req,res)=>{const{shift,recipient_id,summary,todo='',issue='',contribution='',market_data}=req.body||{};if(!['早班','午班','夜班'].includes(shift)||!String(summary).trim()||!recipient_id)return res.status(400).json({error:'班別、交接對象與交接事項為必填'});const recipient=db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(recipient_id);if(!recipient)return res.status(400).json({error:'交接對象不存在或已停用'});if(req.user.role!=='admin'&&recipient.dept!==req.user.dept)return res.status(403).json({error:'只能交接給同部門人員'});const dept=req.user.role==='admin'?(clean(req.body.dept)||recipient.dept):req.user.dept;const special=['水果組','蔬菜組'].includes(dept);let markets={};if(special){if(!String(contribution).trim())return res.status(400).json({error:'水果組與蔬菜組的「本日貢獻度」為必填'});try{markets=typeof market_data==='string'?JSON.parse(market_data||'{}'):(market_data||{})}catch(e){return res.status(400).json({error:'主要批發市場交易行情格式錯誤'})}for(const name of ['三重市場','板橋市場','桃農市場','台中市場','西螺市場','高雄市場']){const v=markets[name]||{};if(v.count!==''&&!/^\d+(\.\d+)?$/.test(String(v.count)))return res.status(400).json({error:`${name}件數只能填數字`});if(v.price!==''&&!/^\d+(\.\d+)?$/.test(String(v.price)))return res.status(400).json({error:`${name}價格只能填數字`})}}const now=new Date().toISOString();const result=db.prepare('INSERT INTO handovers(dept,shift,author_id,recipient_id,summary,todo,issue,today_price,contribution,market_data,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(dept,shift,req.user.id,recipient.id,String(summary).trim(),String(todo).trim()||'無',String(issue).trim()||'無','',special?String(contribution).trim():'',special?JSON.stringify(markets):'{}',now);const msg=`${req.user.name}（${req.user.title}）將 ${dept} ${shift} 交接給您`;db.prepare('INSERT INTO notifications(user_id,handover_id,message,created_at) VALUES(?,?,?,?)').run(recipient.id,result.lastInsertRowid,msg,now);res.status(201).json({id:result.lastInsertRowid,message:'交接已儲存並通知交接對象'})});
app.get('/api/notifications',auth,(req,res)=>res.json(db.prepare(`SELECT n.*,h.dept,h.shift,h.summary,h.todo,h.issue,h.contribution,h.market_data,a.name author_name,a.title author_title FROM notifications n JOIN handovers h ON h.id=n.handover_id JOIN users a ON a.id=h.author_id WHERE n.user_id=? ORDER BY n.id DESC LIMIT 50`).all(req.user.id)));app.post('/api/notifications/:id/read',auth,(req,res)=>{db.prepare('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?').run(new Date().toISOString(),req.params.id,req.user.id);res.json({ok:true})});app.get('/api/health',(req,res)=>res.json({ok:true,service:'handover-system',database:'sqlite'}));app.listen(PORT,()=>console.log(`Handover System API running on http://localhost:${PORT}`));